# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a90bbd706b4eac9a0647add31b17c64fead5ee656ede66402b5aefc62b1b39741784b520ee34137b245c600f9555deb1f5c4eeb4acd32873bb22ac20cf7b7f8d

test:
  secret_key_base: ebbc956b712e0383127b76d2dd03e42465eb4e068fd77f6e05bd892f438df2bf389a5b7b195d34b841b5664c01d28afb607ddf104ea53645a9f4a3571b0277ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
